default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: todos_development

test:
  <<: *default
  database: todos_test

production:
  <<: *default
  database: todos_production
  username: todos
  password: <%= ENV['TODOS_DATABASE_PASSWORD'] %>
